import HeadphoneSVG from '@assets/icons/svg/headphone.svg';
import ChevronRightSVG from '@assets/icons/svg/chevron-right.svg';
import BasketSVG from '@assets/icons/svg/basket.svg';
import DevicesSVG from '@assets/icons/svg/devices.svg';
import BookSVG from '@assets/icons/svg/book.svg';
import HomeSVG from '@assets/icons/svg/home.svg';
import PurchaseSVG from '@assets/icons/svg/purchase.svg';
import BookOpenSVG from '@assets/icons/svg/book-open.svg';
import CalendarSVG from '@assets/icons/svg/calendar.svg';
import CommentSVG from '@assets/icons/svg/comment.svg';
import GlobeSVG from '@assets/icons/svg/globe.svg';
import LockSVG from '@assets/icons/svg/lock.svg';
import BuildingsSVG from '@assets/icons/svg/buildings.svg';
import ShopSVG from '@assets/icons/svg/shop.svg';
import TrendingDownSVG from '@assets/icons/svg/trending-down.svg';
import TrendingUpSVG from '@assets/icons/svg/trending-up.svg';
import TrophySVG from '@assets/icons/svg/trophy.svg';
import TimeSVG from '@assets/icons/svg/time.svg';
import BookReaderSVG from '@assets/icons/svg/book-reader.svg';
import StoreSVG from '@assets/icons/svg/store.svg';

import {Icon} from '../ui/Icon';

export const ChevronRightIcon = Icon.createFromSVG(ChevronRightSVG);
export const HeadphoneIcon = Icon.createFromSVG(HeadphoneSVG);
export const DevicesIcon = Icon.createFromSVG(DevicesSVG);
export const BookIcon = Icon.createFromSVG(BookSVG);
export const BasketIcon = Icon.createFromSVG(BasketSVG);
export const HomeIcon = Icon.createFromSVG(HomeSVG);
export const PurchaseIcon = Icon.createFromSVG(PurchaseSVG);
export const BookOpenIcon = Icon.createFromSVG(BookOpenSVG);
export const CalendarIcon = Icon.createFromSVG(CalendarSVG);
export const CommentIcon = Icon.createFromSVG(CommentSVG);
export const GlobeIcon = Icon.createFromSVG(GlobeSVG);
export const LockIcon = Icon.createFromSVG(LockSVG);
export const BuildingsIcon = Icon.createFromSVG(BuildingsSVG);
export const ShopIcon = Icon.createFromSVG(ShopSVG);
export const TrendingDownIcon = Icon.createFromSVG(TrendingDownSVG);
export const TrendingUpIcon = Icon.createFromSVG(TrendingUpSVG);
export const TrophyIcon = Icon.createFromSVG(TrophySVG);
export const TimeIcon = Icon.createFromSVG(TimeSVG);
export const BookReaderIcon = Icon.createFromSVG(BookReaderSVG);
export const StoreIcon = Icon.createFromSVG(StoreSVG);
